import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import config from "../nuxt.config";

describe("nuxt config", () => {
  it("disables SSR because Tauri has no server", () => {
    expect(config.ssr).toBe(false);
  });

  it("does not ignore the app directory", () => {
    expect(config.ignore).toContain("**/src-tauri/**");
  });

  it("wires up a real stylesheet so Tailwind/@nuxt/ui utility classes work", () => {
    // Regression test: nuxt.config previously had no `css` entry at all, so
    // `.nuxt/ui.css` (generated by the @nuxt/ui module) was never imported
    // into the app bundle. Every Tailwind/@nuxt/ui class in every template
    // was inert and the app rendered in the browser's default serif font.
    expect(config.css).toBeDefined();
    expect(config.css?.length).toBeGreaterThan(0);

    // Resolve each declared css entry against the app/ directory (the "~"
    // alias) and confirm it actually exists on disk, rather than trusting a
    // string that could point at nothing.
    const appDir = fileURLToPath(new URL("../app", import.meta.url));
    const cssEntries = (config.css ?? []).map((entry) => {
      const relative = entry.startsWith("~/") ? entry.slice(2) : entry;
      return `${appDir}/${relative}`;
    });

    for (const path of cssEntries) {
      expect(existsSync(path), `${path} should exist on disk`).toBe(true);
    }

    // At least one of the declared stylesheets must actually pull in
    // Tailwind and @nuxt/ui's generated styles -- otherwise the entry could
    // point at an empty or unrelated file and still "pass".
    const importsRequiredCss = cssEntries.some((path) => {
      const contents = readFileSync(path, "utf-8");
      return contents.includes('"tailwindcss"') && contents.includes('"@nuxt/ui"');
    });
    expect(importsRequiredCss).toBe(true);
  });
});

describe("tauri bundle", () => {
  it("ships the app icon in the macOS bundle", () => {
    // Regression test: v0.1.0 shipped with no `bundle.icon` list, so the .app
    // had no .icns and no CFBundleIconFile, and Finder and the dmg showed
    // macOS's blank placeholder. `tauri dev` uses a built-in default icon, so
    // nothing looked wrong until the release was installed.
    const confPath = fileURLToPath(new URL("../src-tauri/tauri.conf.json", import.meta.url));
    const conf: unknown = JSON.parse(readFileSync(confPath, "utf-8"));
    const icons =
      typeof conf === "object" && conf !== null && "bundle" in conf &&
      typeof conf.bundle === "object" && conf.bundle !== null && "icon" in conf.bundle &&
      Array.isArray(conf.bundle.icon)
        ? conf.bundle.icon.filter((entry): entry is string => typeof entry === "string")
        : [];

    const icns = icons.filter((entry) => entry.endsWith(".icns"));
    expect(icns, "bundle.icon must list an .icns for macOS").not.toHaveLength(0);
    for (const entry of icns) {
      const onDisk = fileURLToPath(new URL(`../src-tauri/${entry}`, import.meta.url));
      expect(existsSync(onDisk), `${entry} should exist under src-tauri/`).toBe(true);
    }
  });
});
